// <auto-generated />
using System;
using Hollis.ResourceDistributor.Functions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hollis.ResourceDistributor.Functions.Migrations
{
    [DbContext(typeof(ResourceDistributorDbContext))]
    partial class ResourceDistributorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ResourceDistributor")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hollis.ResourceDistributor.Functions.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowAnymouse")
                        .HasColumnType("bit");

                    b.Property<string>("Comment")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Resources", "ResourceDistributor");
                });

            modelBuilder.Entity("Hollis.ResourceDistributor.Functions.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClearTextKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("IdentificationName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ClearTextKey");

                    b.ToTable("Users", "ResourceDistributor");
                });

            modelBuilder.Entity("ResourceUser", b =>
                {
                    b.Property<Guid>("AllowUsersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResourcesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AllowUsersId", "ResourcesId");

                    b.HasIndex("ResourcesId");

                    b.ToTable("ResourceUser", "ResourceDistributor");
                });

            modelBuilder.Entity("Hollis.ResourceDistributor.Functions.Entities.Resource", b =>
                {
                    b.OwnsOne("Hollis.ResourceDistributor.Functions.Entities.Resource.RequestCopyHeaderName#List", "RequestCopyHeaderName", b1 =>
                        {
                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Capacity")
                                .HasColumnType("int");

                            b1.HasKey("ResourceId");

                            b1.ToTable("Resources", "ResourceDistributor");

                            b1.ToJson("RequestCopyHeaderName");

                            b1.WithOwner()
                                .HasForeignKey("ResourceId");
                        });

                    b.OwnsOne("System.Collections.Generic.List<string>", "ResponseCopyHeaderName", b1 =>
                        {
                            b1.Property<Guid>("ResourceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Capacity")
                                .HasColumnType("int");

                            b1.HasKey("ResourceId");

                            b1.ToTable("Resources", "ResourceDistributor");

                            b1.ToJson("ResponseCopyHeaderName");

                            b1.WithOwner()
                                .HasForeignKey("ResourceId");
                        });

                    b.Navigation("RequestCopyHeaderName")
                        .IsRequired();

                    b.Navigation("ResponseCopyHeaderName")
                        .IsRequired();
                });

            modelBuilder.Entity("ResourceUser", b =>
                {
                    b.HasOne("Hollis.ResourceDistributor.Functions.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AllowUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hollis.ResourceDistributor.Functions.Entities.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
